using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
    CREATE TABLE IF NOT EXISTS participants (
        Id integer GENERATED BY DEFAULT AS IDENTITY,
        nom text NOT NULL,
        instagram text NOT NULL,
        email text NOT NULL,
        categorie text NOT NULL,
        description text NOT NULL,
        photo_url text NOT NULL,
        certificat_photo boolean NOT NULL,
        inscription_date timestamp with time zone NOT NULL,
        CONSTRAINT PK_participants PRIMARY KEY (Id)
    );
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "participants");
        }
    }
}
